all:traversal largestValues averageOfLevels rightSideView connect maxDepth minDepth invertTree isSymmetric getNodesNum isBanlanced pathofTree sumOfLeftLeaves findBottomLeftValue hasPathSum

traversal:traversal.cpp
	g++ -std=c++11 -o traversal traversal.cpp

largestValues:largestValues.cpp
	g++ -std=c++11 -o largestValues largestValues.cpp

averageOfLevels:averageOfLevels.cpp
	g++ -std=c++11 -o averageOfLevels averageOfLevels.cpp

rightSideView:rightSideView.cpp
	g++ -std=c++11 -o rightSideView rightSideView.cpp

connect:connect.cpp
	g++ -std=c++11 -o connect connect.cpp

maxDepth:maxDepth.cpp
	g++ -std=c++11 -o maxDepth maxDepth.cpp

minDepth:minDepth.cpp
	g++ -std=c++11 -o minDepth minDepth.cpp

invertTree:invertTree.cpp
	g++ -std=c++11 -o invertTree invertTree.cpp

isSymmetric:isSymmetric.cpp
	g++ -std=c++11 -o isSymmetric isSymmetric.cpp

getNodesNum:getNodesNum.cpp
	g++ -std=c++11 -o getNodesNum getNodesNum.cpp

isBanlanced:isBanlanced.cpp
	g++ -std=c++11 -o isBanlanced isBanlanced.cpp

pathofTree:pathofTree.cpp
	g++ -std=c++11 -o pathofTree pathofTree.cpp

sumOfLeftLeaves:sumOfLeftLeaves.cpp
	g++ -std=c++11 -o sumOfLeftLeaves sumOfLeftLeaves.cpp

findBottomLeftValue:findBottomLeftValue.cpp
	g++ -std=c++11 -o findBottomLeftValue findBottomLeftValue.cpp

hasPathSum:hasPathSum.cpp
	g++ -std=c++11 -o hasPathSum hasPathSum.cpp
clean:
	rm -rf traversal largestValues averageOfLevels rightSideView connect maxDepth minDepth invertTree isSymmetric getNodesNum isBanlanced pathofTree sumOfLeftLeaves findBottomLeftValue hasPathSum