all:traversal largestValues averageOfLevels rightSideView connect

traversal:traversal.cpp
	g++ -std=c++11 -o traversal traversal.cpp

largestValues:largestValues.cpp
	g++ -std=c++11 -o largestValues largestValues.cpp

averageOfLevels:averageOfLevels.cpp
	g++ -std=c++11 -o averageOfLevels averageOfLevels.cpp

rightSideView:rightSideView.cpp
	g++ -std=c++11 -o rightSideView rightSideView.cpp

connect:connect.cpp
	g++ -std=c++11 -o connect connect.cpp
clean:
	rm -rf traversal largestValues averageOfLevels rightSideView connect