all:traversal largestValues averageOfLevels rightSideView connect maxDepth minDepth

traversal:traversal.cpp
	g++ -std=c++11 -o traversal traversal.cpp

largestValues:largestValues.cpp
	g++ -std=c++11 -o largestValues largestValues.cpp

averageOfLevels:averageOfLevels.cpp
	g++ -std=c++11 -o averageOfLevels averageOfLevels.cpp

rightSideView:rightSideView.cpp
	g++ -std=c++11 -o rightSideView rightSideView.cpp

connect:connect.cpp
	g++ -std=c++11 -o connect connect.cpp

maxDepth:maxDepth.cpp
	g++ -std=c++11 -o maxDepth maxDepth.cpp

minDepth:minDepth.cpp
	g++ -std=c++11 -o minDepth minDepth.cpp
clean:
	rm -rf traversal largestValues averageOfLevels rightSideView connect maxDepth minDepth