all:weakpoint sharedpoint stockFactory

weakpoint:weakpoint.cpp
	g++ -o weakpoint weakpoint.cpp

sharedpoint:sharedpoint.cpp
	g++ -o sharedpoint sharedpoint.cpp

stockFactory:stockFactory.cpp
	g++ -o stockFactory stockFactory.cpp
clean:
	rm -f weakpoint