all:huawei_1 huawei_2.cpp test

huawei_1:huawei_1.cpp
	g++ -o huawei_1 huawei_1.cpp

huawei_2:huawei_2.cpp
	g++ -o huawei_2 huawei_2.cpp

test:test.cpp
	g++ -o test test.cpp

clean:
	rm -f huawei_1 huawei_2