all:mergesort quicksort tree graph

mergesort:mergesort.cpp
	g++ -o mergesort mergesort.cpp

quicksort:quicksort.cpp
	g++ -o quicksort quicksort.cpp

tree:tree.cpp
	g++ -o tree tree.cpp

graph:graph.cpp
	g++ -o graph graph.cpp

clean:
	rm -f mergesort quicksort tree graph