c11 = -std=c++11

all:useStackToQueue useQueueToStack

useStackToQueue:useStackToQueue.cpp
	g++ $(c11) -o useStackToQueue useStackToQueue.cpp

useQueueToStack:useQueueToStack.cpp
	g++ $(c11) -o useQueueToStack useQueueToStack.cpp

clean:
	rm -f useStackToQueue useQueueToStack
