c11 = -std=c++11

all:useStackToQueue useQueueToStack isValid removeDuplicates evalRPN maxSlidingWindow topKFrequent

useStackToQueue:useStackToQueue.cpp
	g++ $(c11) -o useStackToQueue useStackToQueue.cpp

useQueueToStack:useQueueToStack.cpp
	g++ $(c11) -o useQueueToStack useQueueToStack.cpp

isValid:isValid.cpp
	g++ $(c11) -o isValid isValid.cpp

removeDuplicates:removeDuplicates.cpp
	g++ $(c11) -o removeDuplicates removeDuplicates.cpp

evalRPN:evalRPN.cpp
	g++ $(c11) -o evalRPN evalRPN.cpp

maxSlidingWindow:maxSlidingWindow.cpp
	g++ $(c11) -o maxSlidingWindow maxSlidingWindow.cpp

topKFrequent:topKFrequent.cpp
	g++ $(c11) -o topKFrequent topKFrequent.cpp

clean:
	rm -f useStackToQueue useQueueToStack isValid removeDuplicates evalRPN maxSlidingWindow topKFrequent
 